Add ga tracking configuration
votinginfoproject/vit-configurator pull request #12
Opened 2021-04-14 15:47 UTC by tank157

[Jira Epic](https://democracyworks.atlassian.net/browse/VIP-321)

Pairs with a PR in gttp-relaunch, adds a config section for configuring GA calls to trackers from the embedding page.

2021-04-15 15:08 UTC, alpha-dw commented on src/cljs/vit_configurator/views.cljs
> +     (str "    \"google-analytics-tracker\": " (.stringify js/JSON google-analytics-tracker) ",\n"))
Noting that this seems ok to me from a security standpoint. Exposing a name doesn't seem to open any particular vulnerabilities that may have been present before.

2021-04-15 15:49 UTC, alpha-dw requested changes
Accidentally clicked "Review" for these comments...

Identified some a11y, UX, and CSS fixes

2021-04-15 15:49 UTC, alpha-dw commented on src/cljs/vit_configurator/views/analytics.cljs
> +    [:div
This would be a good place for using `<fieldset>` and `<legend>`, since we have a group of radio buttons.
This example should be good: https://a11y-style-guide.com/style-guide/section-forms.html#kssref-forms-radio-buttons.

2021-04-15 15:49 UTC, alpha-dw commented on src/cljs/vit_configurator/views/analytics.cljs
> +    [:div
The `<label>`s are also missing associations to their respective radio buttons.
This can be explicitly done by adding an `id` attribute for each radio button and adding a `for="<radio button's id>"` attribute to the corresponding `<label>`.

2021-04-15 15:49 UTC, alpha-dw commented on src/cljs/vit_configurator/views/analytics.cljs
> +     [:label.pl-1.pr-4 "Use my tracker with the name below"]
A couple of points here:

UX: It may be nice to have the Tracker Name flow show only if the user has selected the "Use my tracker with the name below" radio button. This would also reduce the amount of dispatches that are fired in the case that the user chooses the first two radio buttons instead.

A11y: The `<label>` and `<input type="text">` here also need to be associated, as in the previous comment about the radio buttons.

A11y: The label text "Use my tracker with the name below" would need to be adjusted, as it features instructions that are orientation-dependent ("below"), which would be problematic for blind users and people with orientation-related disorders.

CSS: The styling in the `:style` attribute seems to be `site.scss`. Do we need it here?

2021-04-19 15:36 UTC, lizstarin commented on src/cljs/vit_configurator/views/analytics.cljs
> +     [:label.pl-1.pr-4 "Use my tracker with the name below"]
Speaking of a11y, this would be something for a separate ticket, but the card toggles themselves aren't accessible.

2021-04-19 15:40 UTC, lizstarin approved these changes
🐥

2021-04-19 15:44 UTC, lizstarin commented on src/sass/site.scss
> +
The inputs in the other cards could use a little `margin-bottom`.

2021-04-19 15:50 UTC, lizstarin commented on src/cljs/vit_configurator/views/analytics.cljs
> +     [:label.pl-1.pr-4 "Use my tracker with the name below"]
@alpha-dw looks like the dispatch only fires on a change event in the input, no? (but I agree that that could be a nicer flow)

2021-06-02 14:30 UTC, alpha-dw approved these changes
🍐

2021-06-15 14:51 UTC, merged